"""empty message

Revision ID: 59838e0324e7
Revises: af127e9088ee
Create Date: 2023-11-04 11:37:10.406849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59838e0324e7'
down_revision = 'af127e9088ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('posted_on')

    # ### end Alembic commands ###
